#!/bin/bash
# collect-binaries.sh - Script to set up directory structure for embedded Tesseract binaries

if [ ! -d "src" ]; then
  echo "Please run this script from the project root directory."
  exit 1
fi

echo "🔧 Setting up directory structure for embedded Tesseract binaries..."

RESOURCES_DIR="src/main/resources"

# Create directories for native binaries
mkdir -p "$RESOURCES_DIR/native/windows-x64"
mkdir -p "$RESOURCES_DIR/native/linux-x64"
mkdir -p "$RESOURCES_DIR/native/macos-x64"
mkdir -p "$RESOURCES_DIR/tessdata"

echo "✓ Directory structure created!"
echo ""
echo "📁 Place your platform-specific binaries in the following directories:"
echo ""
echo "Windows binaries:"
echo "  → $RESOURCES_DIR/native/windows-x64/tesseract.exe"
echo "  → $RESOURCES_DIR/native/windows-x64/libleptonica-5.dll"
echo "  → $RESOURCES_DIR/native/windows-x64/libtesseract-5.dll"
echo ""
echo "Linux binaries:"
echo "  → $RESOURCES_DIR/native/linux-x64/tesseract"
echo "  → $RESOURCES_DIR/native/linux-x64/libtesseract.so.5"
echo "  → $RESOURCES_DIR/native/linux-x64/libleptonica.so.5"
echo ""
echo "macOS binaries:"
echo "  → $RESOURCES_DIR/native/macos-x64/tesseract"
echo "  → $RESOURCES_DIR/native/macos-x64/libtesseract.5.dylib"
echo "  → $RESOURCES_DIR/native/macos-x64/libleptonica.5.dylib"
echo ""
echo "Tessdata files:"
echo "  → $RESOURCES_DIR/tessdata/eng.traineddata"
echo "  → $RESOURCES_DIR/tessdata/fra.traineddata"
echo "  → $RESOURCES_DIR/tessdata/deu.traineddata"
echo ""
echo "📋 Instructions to obtain binaries:"
echo ""
echo "Windows:"
echo "  1. Download from: https://github.com/UB-Mannheim/tesseract/wiki"
echo "  2. Install Tesseract"
echo "  3. Copy files from installation directory to Windows folder above"
echo ""
echo "Linux (Ubuntu/Debian):"
echo "  1. Run: sudo apt-get install tesseract-ocr libtesseract-dev"
echo "  2. Copy /usr/bin/tesseract to Linux folder above"
echo "  3. Copy library files from /usr/lib/x86_64-linux-gnu/ to Linux folder above"
echo ""
echo "macOS:"
echo "  1. Run: brew install tesseract"
echo "  2. Copy /usr/local/bin/tesseract (or /opt/homebrew/bin/tesseract on M1) to macOS folder above"
echo "  3. Copy library files from /usr/local/lib/ (or /opt/homebrew/lib/) to macOS folder above"
echo ""
echo "Tessdata files:"
echo "  1. Download from: https://github.com/tesseract-ocr/tessdata"
echo "  2. Download .traineddata files for languages you need"
echo "  3. Place in tessdata folder above"
echo ""
echo "⚠️  Note: Each tessdata file is ~10-15MB, so choose only languages you need!"
echo ""
echo "Note: This script does NOT download binaries automatically. Please follow the instructions above to obtain and place them."
echo ""
echo "🚀 After placing all binaries, run: mvn clean package"
echo "✅ Setup complete!"
